version: "3.1"
networks:
  web:
    external: true
  internal:
    external: false
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./dbs:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - internal
      - web
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - web
    depends_on:
      - db