version: "3.1"
networks:
  web:
    external: true
  internal:
    external: false
services:
  imgsrv:
    image: nginx:latest
    container_name: imgsrv
    restart: unless-stopped
    ports:
      - 8089:80
    volumes:
      - ./img_db:/usr/share/nginx/html
    networks:
      - web
  db:
    image: postgres
    restart: always
    volumes:
      - ./dbs:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - internal
      - web
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - web
    depends_on:
      - db
  apiserver:
    image: clojure
    container_name: "stronghand_3e_api"
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/myapp
    networks:
      - web
      - internal
    working_dir: /usr/src/myapp
    command: sh -c "lein do clean, ring uberjar && java -jar target/server.jar"